version: "3.9"

services:

  # ########################################################################## #
  # Common chainweb node spec
  node:
    labels:
      com.chainweb.devnet.description: "Devnet Node"
      com.chainweb.devnet.node: ""

    # image: ghcr.io/kadena-io/chainweb-node/ubuntu:latest
    image: ${CHAINWEB_NODE_IMAGE}
    restart: unless-stopped
    stop_grace_period: 20s
    stop_signal: SIGINT
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    expose:
    - "1789"
    - "1848"
    configs:
    - source: chainweb-node.common
      target: /chainweb/config/chainweb-node.common.yaml
      mode: 0440
    - source: chainweb-node.logging
      target: /chainweb/config/chainweb-node.logging.yaml
      mode: 0440

    entrypoint:
    - /chainweb/chainweb-node
    # Runtime Settings
    - +RTS
    - -T
    - -H400M
    - -A64M
    - -RTS
    # Common Configuration
    - --config-file=config/chainweb-node.common.yaml
    - --config-file=config/chainweb-node.logging.yaml

    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        delay: 60s
        order: stop-first

    healthcheck:
      test: 
      - 'CMD'
      - '/bin/bash'
      - '-c'
      - 'exec 3<>/dev/tcp/localhost/1848; printf "GET /health-check HTTP/1.1\r\nhost: http://localhost:1848\r\nConnection: close\r\n\r\n" >&3; grep -q "200 OK" <&3 || exit 1'
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10s

